### ISSUE TITLE
\Drupal\Core\Session\AccountInterface::getUsername() is deprecated in Drupal 8.0.0, will be removed before Drupal 9.0.0

### ISSUE THREAD

**Issue by Kopin1** [guncha25/drupal-codeception#10]
Need to use new class for get user name:

Use \Drupal\Core\Session\AccountInterface::getAccountName() or \Drupal\user\UserInterface::getDisplayName() instead. See https://www.drupal.org/node/2572493

**Comment by guncha25** [comment]
Thank you  @Kopin1 fixed in 9.0.1

**Comment by Kopin1** [comment]
Hi, thank you for the quick response. After testing the lastest release 9.0.1 i am getting:
`[PHPUnit\Framework\AssertionFailedError]
  Could not load entities of type media by uid 51
  Could not load entities of type node by uid 51`

When the cleanup process is done.
I am guessing it has something to do with the class change.

**Comment by guncha25** [comment]
Sorry. Did blind coding. Should be fixed in 9.0.2. @Kopin1
