### ISSUE TITLE
Exception thrown and test fails when entity does not contain uid property

### ISSUE THREAD

**Issue by mgalang** [guncha25/drupal-codeception#4]
### Issue description:
The `deleteUsersContent` method deletes user created entities, the method uses `loadByProperties` of the entity type manager storage. 

This causes an error when an entity does not have the `uid` property (as was the case with the latest paragraph module update), It then incorrectly fails the tests.

### Proposal/Possible solutions:
Check if entity contains the `uid` property before trying to load entities using the `uid` property.

See: 
https://github.com/guncha25/drupal-codeception/blob/3f510b31315e73d4d6792a4c4cb01a34cb5da7c3/src/Codeception/Module/DrupalUser.php#L201

**Comment by guncha25** [comment]
Thank you  @mgalang  fixed in 9.0.1
