### ISSUE TITLE
Error in bootstrap

### ISSUE THREAD

**Issue by TomiMikola** [guncha25/drupal-codeception#9]
`Error: Call to undefined method Codeception\TestDrupalKernel::prepareLegacyRequest() in /app/vendor/guncha25/drupal-codeception/src/Codeception/Module/DrupalBootstrap.php on line 74`

Using the latest versions:
codeception/codeception 4.1.7
guncha25/drupal-codeception 8.0.16

**Comment by guncha25** [comment]
I assume Drupal 9 as https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21DrupalKernel.php/function/DrupalKernel%3A%3AprepareLegacyRequest/8.9.x indicates its deprecated and suggests using DrupalKernel::boot() and DrupalKernel::preHandle() instead.

This needs to be included in drupal-codeception:9.x

**Comment by guncha25** [comment]
Fixed in version 9.0.0
